// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H

#include "WPILib.h"

class OI {
private:
	std::shared_ptr<Joystick> driverWheel;
	std::shared_ptr<Joystick> driverStick;

	std::shared_ptr<JoystickButton> dA;
	std::shared_ptr<JoystickButton> dB;
	std::shared_ptr<JoystickButton> dX;
	std::shared_ptr<JoystickButton> dY;
	std::shared_ptr<JoystickButton> dLB;
	std::shared_ptr<JoystickButton> dRB;
	std::shared_ptr<JoystickButton> dL3;
	std::shared_ptr<JoystickButton> dR3;
	std::shared_ptr<JoystickButton> dStart;
	std::shared_ptr<JoystickButton> dBack;


	public:
	OI();

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	std::shared_ptr<Joystick> GetDriverStick();
	std::shared_ptr<Joystick> GetDriverWheel();
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	double GetDriverStickAxis() const;
	double GetDriverWheelAxis() const;

	static const int kButtonA_ID = 1;
	static const int kButtonB_ID = 2;
	static const int kButtonX_ID = 3;
	static const int kButtonY_ID = 4;
	static const int kButtonLB_ID = 5;
	static const int kButtonRB_ID = 6;
	static const int kButtonBack_ID = 7;
	static const int kButtonStart_ID = 8;
	static const int kButtonL3_ID = 9;
	static const int kButtonR3_ID = 10;
};

#endif
