// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Robot.h"

std::shared_ptr<Chassis> Robot::chassis;
std::unique_ptr<OI> Robot::oi;


void Robot::RobotInit() {

	RobotMap::init();
	chassis.reset(new Chassis());

	//Have OI last to avoid pointing to null commands
	oi.reset(new OI());

	// instantiate the command used for the autonomous period

}

/**
 * This function is called when the disabled button is hit.
 * You can use it to reset subsystems before shutting down.
 */
void Robot::DisabledInit(){

}

void Robot::DisabledPeriodic() {
	Scheduler::GetInstance()->Run();
}

void Robot::AutonomousInit() {

}

void Robot::AutonomousPeriodic() {
	Scheduler::GetInstance()->Run();
}

void Robot::TeleopInit() {

}

void Robot::TeleopPeriodic() {
	Scheduler::GetInstance()->Run();

	SmartDashboard::PutNumber("Driver Left Y", oi->getDriverLeftAxis());
	SmartDashboard::PutNumber("Driver Right Y", oi->getDriverRightAxis());

	SmartDashboard::PutNumber("Left1Wheel Error", RobotMap::chassisLeft1Wheel->Get() - RobotMap::chassisLeft1Wheel->GetEncPosition());
	SmartDashboard::PutNumber("Right1Wheel Error", RobotMap::chassisRight1Wheel->Get() - RobotMap::chassisRight1Wheel->GetEncPosition());

	SmartDashboard::PutNumber("Left1Wheel Position", RobotMap::chassisLeft1Wheel->GetEncPosition());
	SmartDashboard::PutNumber("Right1Wheel Position", RobotMap::chassisRight1Wheel->GetEncPosition());

	SmartDashboard::PutNumber("Left1Wheel Target", RobotMap::chassisLeft1Wheel->Get());
	SmartDashboard::PutNumber("Right1Wheel Target", RobotMap::chassisRight1Wheel->Get());

}

void Robot::TestPeriodic() {

}

START_ROBOT_CLASS(Robot);

