// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"


/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:

	//..........Talons and Solenoids..........

	//..........chassis..........

	static std::shared_ptr<CANTalon> chassisLeft1Wheel;
	static std::shared_ptr<CANTalon> chassisLeft2Wheel;
	static std::shared_ptr<CANTalon> chassisLeft3Wheel;
	static std::shared_ptr<CANTalon> chassisRight1Wheel;
	static std::shared_ptr<CANTalon> chassisRight2Wheel;
	static std::shared_ptr<CANTalon> chassisRight3Wheel;

	static std::shared_ptr<DoubleSolenoid> chassisShifter;
	static std::shared_ptr<DoubleSolenoid> chassisKickstand;


	//...........intake........

	static std::shared_ptr<CANTalon> intakeHorizontalBands;
	static std::shared_ptr<CANTalon> intakeVerticalBands;

	//..........shooter..........

	static std::shared_ptr<CANTalon> shooterLeftFlywheel;
	static std::shared_ptr<CANTalon> shooterRightFlywheel;
	static std::shared_ptr<CANTalon> shooterRoller;

	static std::shared_ptr<DoubleSolenoid> shooterLifter;

	//..........IDs..........

	//..........arms..........

	static std::shared_ptr<CANTalon> armsLeftBrazo;
	static std::shared_ptr<CANTalon> armsRightBrazo;

	//..........chassis..........

	static const int kLeft1ID = 1;
	static const int kLeft2ID = 2;
	static const int kLeft3ID = 3;
	static const int kRight1ID = 4;
	static const int kRight2ID = 5;
	static const int kRight3ID = 6;

	static const int kShifterF = 0;
	static const int kShifterR = 3;
	static const int kKickstandF = 4;
	static const int kKickstandR = 5;

	//...........intake........

	static const int kHoriBandsID = 7;
	static const int kVerBandsID = 8;


	//..........shooter..........

	static const int kLeftFlywheelID = 11;
	static const int kRightFlywheelID = 12;
	static const int kRollerID = 13;
	static const int kLifterF = 1;
	static const int kLifterR = 2;

	//..........arms..........

	static std::shared_ptr<CANTalon> armLeft;
	static std::shared_ptr<CANTalon> armRight;

	//..........arms..........

	static const int kArmLeft  = 20;
	static const int kArmRight = 21;


	//.........Buttons.....
	static void init();




};
#endif
