// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"


/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:

	//..........chassis..........

	static std::shared_ptr<CANTalon> chassisLeft1Wheel;
	static std::shared_ptr<CANTalon> chassisLeft2Wheel;
	static std::shared_ptr<CANTalon> chassisLeft3Wheel;
	static std::shared_ptr<CANTalon> chassisRight1Wheel;
	static std::shared_ptr<CANTalon> chassisRight2Wheel;
	static std::shared_ptr<CANTalon> chassisRight3Wheel;

	static std::shared_ptr<DoubleSolenoid> chassisShifter;
	static std::shared_ptr<DoubleSolenoid> chassisKickstand;

	//..........shooter..........

	static std::shared_ptr<CANTalon> shooterLeftFlywheel;
	static std::shared_ptr<CANTalon> shooterRightFlywheel;
	static std::shared_ptr<CANTalon> shooterRoller;

	static std::shared_ptr<DoubleSolenoid> shooterLifter;

	//..........intake..........


	//..........arms..........


	//..........chassis..........

/*private:
	const int kLeft1ID = 1;
	const int kLeft2ID = 2;
	const int kLeft3ID = 3;
	const int kRight1ID = 4;
	const int kRight2ID = 5;
	const int kRight3ID = 6;

	const int kShifterF = 0;
	const int kShifterR = 3;
	const int kKickstandF = 4;
	const int kKickstandR = 5;

	//..........shooter..........

	const int kLeftFlywheelID = 11;
	const int kRightFlywheelID = 12;
	const int kRollerID = 13;

	const int kLifterF = 1;
	const int kLifterR = 2;
*/
	static void init();




};
#endif
